from .usuario import Usuarios as UsuariosResource
from .usuario import Usuario as UsuarioResource
from .usuario import UsuariosAlumnos as UsuariosAlumnosResource
from .usuario import UsuarioProfesor as UsuarioProfesorResource
from .usuario import UsuarioAlumno as UsuarioAlumnoResource
from .planificacion import PlanificacionAlumno as PlanificacionAlumnoResource
from .planificacion import PlanificacionesProfesores as PlanificacionesProfesoresResource
from .planificacion import PlanificacionProfesor as PlanificacionProfesorResource
from .profesor import ProfesorClases as ProfesorClasesResource
from .pago import Pago as PagoResource
from .login import Login as LoginResource
